// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4zAyzpdRcUk0q05_CktI813UDy-rc6FU',
    appId: '1:109749738479:web:76348b41acf99f194b341a',
    messagingSenderId: '109749738479',
    projectId: 'brandbuilders-ed4e2',
    authDomain: 'brandbuilders-ed4e2.firebaseapp.com',
    storageBucket: 'brandbuilders-ed4e2.firebasestorage.app',
    measurementId: 'G-LY18HX3LF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHbCmaJJqRWp4xlz0oA4xncsXb4cm05M',
    appId: '1:109749738479:android:f9dafd7185ee4b924b341a',
    messagingSenderId: '109749738479',
    projectId: 'brandbuilders-ed4e2',
    storageBucket: 'brandbuilders-ed4e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDTNbbX5EKAc-5LaD6auVYwMu4AvJBfxU',
    appId: '1:109749738479:ios:f61f9300fb4fb2cd4b341a',
    messagingSenderId: '109749738479',
    projectId: 'brandbuilders-ed4e2',
    storageBucket: 'brandbuilders-ed4e2.firebasestorage.app',
    iosBundleId: 'com.example.photomerge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDTNbbX5EKAc-5LaD6auVYwMu4AvJBfxU',
    appId: '1:109749738479:ios:f61f9300fb4fb2cd4b341a',
    messagingSenderId: '109749738479',
    projectId: 'brandbuilders-ed4e2',
    storageBucket: 'brandbuilders-ed4e2.firebasestorage.app',
    iosBundleId: 'com.example.photomerge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4zAyzpdRcUk0q05_CktI813UDy-rc6FU',
    appId: '1:109749738479:web:5cb1571db3eef4794b341a',
    messagingSenderId: '109749738479',
    projectId: 'brandbuilders-ed4e2',
    authDomain: 'brandbuilders-ed4e2.firebaseapp.com',
    storageBucket: 'brandbuilders-ed4e2.firebasestorage.app',
    measurementId: 'G-GGRCY0MDC7',
  );
}
